# Generated by Django 2.0 on 2018-09-12 13:50

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_auto_20180911_0826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walletbalance',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20),
        ),
    ]
