# Generated by Django 2.0 on 2018-09-13 12:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer', '0006_auto_20180912_0650'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.FileField(upload_to='addtion_files')),
            ],
        ),
        migrations.CreateModel(
            name='FavouriteWriters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('writers', models.CharField(max_length=250, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InvitedWriters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invitees', models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('order_uuid', models.IntegerField(unique=True)),
                ('order_type', models.CharField(choices=[('Essay (any type)', 'Essay (any type)'), ('Admission Essay', 'Admission Essay'), ('Annotated Bibliography', 'Annotated Bibliography'), ('Article Review', 'Article Review'), ('Book / Movie Review', 'Book / Movie Review'), ('Business Plan', 'Business Plan'), ('Case Study', 'Case Study'), ('Coursework', 'Coursework'), ('Creative Writing', 'Creative Writing'), ('Critical Thinking / Review', 'Critical Thinking / Review'), ('Literature Review', 'Literature Review'), ('Multiple choice question', 'Multiple choice question'), ('Presentation or Speech', 'Presentation or Speech'), ('Reflective Writing', 'Reflective Writing'), ('Report', 'Report'), ('Research Paper', 'Research Paper'), ('Research Proposal', 'Research Proposal'), ('Term Paper', 'Term Paper')], max_length=250)),
                ('pages', models.CharField(max_length=250)),
                ('service', models.CharField(choices=[('Writing', 'Writing'), ('Editing', 'Editing'), ('Rewriting', 'Rewriting')], max_length=250)),
                ('deadline', models.DateTimeField()),
                ('sources', models.CharField(choices=[('0 source', '0 source'), ('1 source', '1 source'), ('2 source', '2 source'), ('3 source', '3 source'), ('4 source', '4 source'), ('5 source', '5 source'), ('7 source', '7 source')], max_length=250)),
                ('style', models.CharField(choices=[('Harvard', 'Harvard'), (' APA', ' APA'), ('Chicago/Turabian', 'Chicago/Turabian'), ('Not Applicable', 'Not Applicable'), (' Other', ' Other')], max_length=250)),
                ('subject', models.CharField(choices=[('Advertising', 'Advertising'), ('Aeronautics', 'Aeronautics'), ('African-American Studies', 'African-American Studies'), ('Agricultural Studies', 'Agricultural Studies'), ('Alternative Medicine', 'Alternative Medicine'), ('American History', 'American History'), ('American Literature', 'American Literature'), ('Anthropology', 'Anthropology'), ('Antique Literature', 'Antique Literature'), ('Application Essay', 'Application Essay'), ('Architecture', 'Architecture'), ('Art', 'Art'), ('Asian Literature', 'Asian Literature'), ('Asian Studies', 'Asian Studies'), ('Astronomy', 'Astronomy'), ('Aviation', 'Aviation'), ('Biology', 'Biology'), ('Business', 'Business'), ('Canadian Studies', 'Canadian Studies'), ('Case Study', 'Case Study'), ('Chemistry', 'Chemistry'), ('Communication Strategies', 'Communication Strategies'), ('Communications and Media', 'Communications and Media'), ('Company Analysis', 'Company Analysis'), ('Computer Science', 'Computer Science'), ('Creative Writing', 'Creative Writing'), ('Criminology', 'Criminology'), ('Dance', 'Dance'), ('Design Analysis', 'Design Analysis'), ('Drama', 'Drama'), ('E-Commerce', 'E-Commerce'), ('East European Studies', 'East European Studies'), ('Economics', 'Economics'), ('Education', 'Education'), ('Education Theories', 'Education Theories'), ('Engineering', 'Engineering'), ('English', 'English'), ('English Literature', 'English Literature'), ('Environmental Issues', 'Environmental Issues'), ('Ethics', 'Ethics'), ('Finance', 'Finance'), ('Geography', 'Geography'), ('Geology', 'Geology'), ('Healthcare', 'Healthcare'), ('History', 'History'), ('Holocaust', 'Holocaust'), ('International Affairs/Relations', 'International Affairs/Relations'), ('Internet', 'Internet'), ('Investment', 'Investment'), ('IT Management', 'IT Management'), ('Journalism', 'Journalism'), ('Latin-American Studies', 'Latin-American Studies'), ('Law', 'Law'), ('Legal Issues', 'Legal Issues'), ('Linguistics', 'Linguistics'), ('Literature', 'Literature'), ('Logistics', 'Logistics'), ('Management', 'Management'), ('Marketing', 'Marketing'), ('Mathematics', 'Mathematics'), ('Medicine and Health', 'Medicine and Health'), ('Movies', 'Movies'), (' Music', ' Music'), (' Native-American Studies', 'Native-American Studies'), ('Nature', 'Nature'), ('Nursing', 'Nursing'), ('Nutrition', 'Nutrition'), ('Painting', 'Painting'), ('Pedagogy', 'Pedagogy'), ('Pharmacology', 'Pharmacology'), ('Philosophy', 'Philosophy'), ('Physics', 'Physics'), ('Political Science', 'Political Science'), ('Psychology', 'Psychology'), ('Public Relations', ' Public Relations'), ('Religion and Theology', 'Religion and Theology'), ('Shakespeare Studies', 'Shakespeare Studies'), ('Sociology', 'Sociology'), ('Sport', 'Sport'), ('Teacher', 'Teacher'), ('Technology', 'Technology'), ('Theatre', 'Theatre'), ('Tourism', 'Tourism'), ('Trade', 'Trade'), ('Web design', 'Web design'), ('West European Studies', 'West European Studies'), ('Other', 'Other')], max_length=250)),
                ('level', models.CharField(choices=[('School', 'School'), ('University', 'University'), ('Dictorate', 'Dictorate')], max_length=250)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='invitedwriters',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Order'),
        ),
        migrations.AddField(
            model_name='additionalfiles',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Order'),
        ),
    ]
