# Generated by Django 2.0 on 2018-09-14 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0010_auto_20180913_0826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favouritewriters',
            name='user',
        ),
        migrations.DeleteModel(
            name='FavouriteWriters',
        ),
    ]
