# Generated by Django 2.0 on 2018-09-17 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0013_auto_20180917_1519'),
    ]

    operations = [
        migrations.RenameField(
            model_name='declined',
            old_name='hired',
            new_name='declined',
        ),
        migrations.AlterField(
            model_name='order',
            name='level',
            field=models.CharField(choices=[('School', 'School'), ('University', 'University'), ('Dictorate', 'Dictorate')], default='essay level', max_length=250),
        ),
        migrations.AlterField(
            model_name='order',
            name='sources',
            field=models.CharField(choices=[('0 source', '0 source'), ('1 source', '1 source'), ('2 source', '2 source'), ('3 source', '3 source'), ('4 source', '4 source'), ('5 source', '5 source'), ('7 source', '7 source')], default='essay sources', max_length=250),
        ),
        migrations.AlterField(
            model_name='order',
            name='style',
            field=models.CharField(choices=[('Harvard', 'Harvard'), (' APA', ' APA'), ('Chicago/Turabian', 'Chicago/Turabian'), ('Not Applicable', 'Not Applicable'), (' Other', ' Other')], default='essay style', max_length=250),
        ),
        migrations.AlterField(
            model_name='order',
            name='subject',
            field=models.CharField(choices=[('Advertising', 'Advertising'), ('Aeronautics', 'Aeronautics'), ('African-American Studies', 'African-American Studies'), ('Agricultural Studies', 'Agricultural Studies'), ('Alternative Medicine', 'Alternative Medicine'), ('American History', 'American History'), ('American Literature', 'American Literature'), ('Anthropology', 'Anthropology'), ('Antique Literature', 'Antique Literature'), ('Application Essay', 'Application Essay'), ('Architecture', 'Architecture'), ('Art', 'Art'), ('Asian Literature', 'Asian Literature'), ('Asian Studies', 'Asian Studies'), ('Astronomy', 'Astronomy'), ('Aviation', 'Aviation'), ('Biology', 'Biology'), ('Business', 'Business'), ('Canadian Studies', 'Canadian Studies'), ('Case Study', 'Case Study'), ('Chemistry', 'Chemistry'), ('Communication Strategies', 'Communication Strategies'), ('Communications and Media', 'Communications and Media'), ('Company Analysis', 'Company Analysis'), ('Computer Science', 'Computer Science'), ('Creative Writing', 'Creative Writing'), ('Criminology', 'Criminology'), ('Dance', 'Dance'), ('Design Analysis', 'Design Analysis'), ('Drama', 'Drama'), ('E-Commerce', 'E-Commerce'), ('East European Studies', 'East European Studies'), ('Economics', 'Economics'), ('Education', 'Education'), ('Education Theories', 'Education Theories'), ('Engineering', 'Engineering'), ('English', 'English'), ('English Literature', 'English Literature'), ('Environmental Issues', 'Environmental Issues'), ('Ethics', 'Ethics'), ('Finance', 'Finance'), ('Geography', 'Geography'), ('Geology', 'Geology'), ('Healthcare', 'Healthcare'), ('History', 'History'), ('Holocaust', 'Holocaust'), ('International Affairs/Relations', 'International Affairs/Relations'), ('Internet', 'Internet'), ('Investment', 'Investment'), ('IT Management', 'IT Management'), ('Journalism', 'Journalism'), ('Latin-American Studies', 'Latin-American Studies'), ('Law', 'Law'), ('Legal Issues', 'Legal Issues'), ('Linguistics', 'Linguistics'), ('Literature', 'Literature'), ('Logistics', 'Logistics'), ('Management', 'Management'), ('Marketing', 'Marketing'), ('Mathematics', 'Mathematics'), ('Medicine and Health', 'Medicine and Health'), ('Movies', 'Movies'), (' Music', ' Music'), (' Native-American Studies', 'Native-American Studies'), ('Nature', 'Nature'), ('Nursing', 'Nursing'), ('Nutrition', 'Nutrition'), ('Painting', 'Painting'), ('Pedagogy', 'Pedagogy'), ('Pharmacology', 'Pharmacology'), ('Philosophy', 'Philosophy'), ('Physics', 'Physics'), ('Political Science', 'Political Science'), ('Psychology', 'Psychology'), ('Public Relations', ' Public Relations'), ('Religion and Theology', 'Religion and Theology'), ('Shakespeare Studies', 'Shakespeare Studies'), ('Sociology', 'Sociology'), ('Sport', 'Sport'), ('Teacher', 'Teacher'), ('Technology', 'Technology'), ('Theatre', 'Theatre'), ('Tourism', 'Tourism'), ('Trade', 'Trade'), ('Web design', 'Web design'), ('West European Studies', 'West European Studies'), ('Other', 'Other')], default='essay subject', max_length=250),
        ),
    ]
