# Generated by Django 2.0 on 2018-09-17 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0014_auto_20180917_1541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='declined',
            name='declined',
        ),
        migrations.RemoveField(
            model_name='declined',
            name='user',
        ),
        migrations.RemoveField(
            model_name='shortlistedbid',
            name='shortlisted_writer',
        ),
        migrations.RemoveField(
            model_name='shortlistedbid',
            name='user',
        ),
        migrations.DeleteModel(
            name='Declined',
        ),
        migrations.DeleteModel(
            name='ShortListedBid',
        ),
    ]
