# Generated by Django 2.0 on 2018-09-19 16:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0017_shortlisted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='description',
            field=models.TextField(validators=[django.core.validators.MinValueValidator(limit_value=20, message='Too Short')]),
        ),
        migrations.AlterField(
            model_name='order',
            name='pages',
            field=models.CharField(choices=[('1 page / 275 words', '1 page / 275 words'), ('2 pages / 550 words', '2 pages / 550 words'), ('3 pages / 825 words', '3 pages / 825 words'), ('4 pages / 1100 words', '4 pages / 1100 words'), ('5 pages / 1375 words', '5 pages / 1375 words'), ('6 pages / 1650 words', '6 pages / 1650 words'), ('7 pages / 1925 words', '7 pages / 1925 words'), ('9 pages / 2200 words', '9 pages / 2200 words'), ('10 pages / 2750 words', '10 pages / 2750 words'), ('11 pages / 3025 words', '11 pages / 3025 words'), ('12 pages / 3300 words', '12 pages / 3300 words'), ('13 pages / 3575 words', '13 pages / 3575 words'), ('14 pages / 3850 words', '14 pages / 3850 words'), ('15 pages/ 4125 words', '15 pages/ 4125 words'), ('16 pages / 4400 words', '16 pages / 4400 words'), ('17 pages / 4675  words', '17 pages / 4675  words'), ('18 pages / 4950 words', '18 pages / 4950 words'), ('19 pages / 5225 words', '19 pages / 5225 words'), ('20 pages / 5500 words', '20 pages / 5500 words'), ('21 pages / 5775 words', '21 pages / 5775 words'), ('22 pages / 6050 words', '22 pages / 6050 words'), ('23 pages / 6325 words', '23 pages / 6325 words'), ('24 pages / 6600  words', '24 pages / 6600  words'), ('25 pages / 6875 words', '25 pages / 6875 words'), ('26 pages / 7150 words', '26 pages / 7150 words'), ('27 pages / 7425 words', '27 pages / 7425   words'), ('28 pages / 7700 words', '28 pages / 7700 words'), ('29 pages / 7975 words', '29 pages / 7975 words'), ('30 pages / 8250  words', '30 pages / 8250  words')], default='page choice', max_length=250),
        ),
    ]
