# Generated by Django 2.0 on 2018-09-21 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0019_auto_20180920_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='favouritewriters',
            name='in_fav',
            field=models.BooleanField(default=False),
        ),
    ]
