# Generated by Django 2.0 on 2018-09-21 17:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0020_favouritewriters_in_fav'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favouritewriters',
            name='favorite_writers',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorite_writers', to=settings.AUTH_USER_MODEL),
        ),
    ]
