# Generated by Django 2.0 on 2018-09-21 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0021_auto_20180921_1000'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favouritewriters',
            old_name='in_fav',
            new_name='is_fav',
        ),
    ]
