# Generated by Django 2.0 on 2018-09-22 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0022_auto_20180921_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='in_progress',
            field=models.BooleanField(default=False),
        ),
    ]
