# Generated by Django 2.0 on 2018-09-23 18:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0024_auto_20180922_1205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='additionalfiles',
            name='user',
        ),
        migrations.AddField(
            model_name='additionalfiles',
            name='user',
            field=models.ManyToManyField(related_name='additional_filesc', to='customer.Order'),
        ),
        migrations.AlterField(
            model_name='invitedwriters',
            name='invitees',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitees', to=settings.AUTH_USER_MODEL),
        ),
    ]
