# Generated by Django 2.0 on 2018-09-23 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0025_auto_20180923_1115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='additionalfiles',
            name='user',
        ),
        migrations.AddField(
            model_name='additionalfiles',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='additional_filesc', to='customer.Order'),
            preserve_default=False,
        ),
    ]
