# Generated by Django 2.0 on 2018-09-24 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0026_auto_20180923_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitedwriters',
            name='invited',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='deadline',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
