# Generated by Django 2.0 on 2018-10-01 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0031_auto_20180926_0707'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitedwriters',
            name='invitees',
        ),
        migrations.RemoveField(
            model_name='invitedwriters',
            name='user',
        ),
        migrations.DeleteModel(
            name='InvitedWriters',
        ),
    ]
