# Generated by Django 2.0 on 2018-10-02 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0032_auto_20181001_1131'),
    ]

    operations = [
        migrations.RenameField(
            model_name='additionalfiles',
            old_name='files',
            new_name='file_upload',
        ),
    ]
