# Generated by Django 2.0 on 2018-10-04 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0034_auto_20181002_0834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalfiles',
            name='file_upload',
            field=models.FileField(upload_to='addition_files'),
        ),
    ]
