# Generated by Django 2.0 on 2018-10-06 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0035_auto_20181003_1723'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offers', models.IntegerField(default=0)),
                ('offer_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='customer.Order')),
            ],
        ),
        migrations.RemoveField(
            model_name='shortlisted',
            name='short_id',
        ),
        migrations.RemoveField(
            model_name='shortlisted',
            name='writer',
        ),
        migrations.DeleteModel(
            name='ShortListed',
        ),
    ]
