# Generated by Django 2.0 on 2018-10-08 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0037_auto_20181006_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('Essay (any type)', 'Essay (any type)'), ('Admission Essay', 'Admission Essay'), ('Annotated Bibliography', 'Annotated Bibliography'), ('Article Review', 'Article Review'), ('Book / Movie Review', 'Book / Movie Review'), ('Business Plan', 'Business Plan'), ('Case Study', 'Case Study'), ('Coursework', 'Coursework'), ('Creative Writing', 'Creative Writing'), ('Critical Thinking / Review', 'Critical Thinking / Review'), ('Literature Review', 'Literature Review'), ('Multiple choice question', 'Multiple choice question'), ('Presentation or Speech', 'Presentation or Speech'), ('Reflective Writing', 'Reflective Writing'), ('Report', 'Report'), ('Research Paper', 'Research Paper'), ('Research Proposal', 'Research Proposal'), ('Term Paper', 'Term Paper')], help_text='Select essay type', max_length=250),
        ),
    ]
