# Generated by Django 2.0 on 2018-09-17 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180906_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='login_status',
            field=models.BooleanField(default=False),
        ),
    ]
