# Generated by Django 2.0 on 2018-09-25 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20180919_0458'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_writer',
        ),
    ]
