# Generated by Django 2.0 on 2018-09-17 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writers', '0002_auto_20180917_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='bids',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bids',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bids',
            name='declined',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bids',
            name='in_progress',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bids',
            name='shortlisted',
            field=models.BooleanField(default=False),
        ),
    ]
