# Generated by Django 2.0 on 2018-09-19 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writers', '0004_auto_20180919_0535'),
    ]

    operations = [
        migrations.AddField(
            model_name='writersprofile',
            name='full_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='writersprofile',
            name='payment_method',
            field=models.CharField(default='Paypal', editable=False, max_length=50),
        ),
        migrations.AddField(
            model_name='writersprofile',
            name='paypal_id',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
