# Generated by Django 2.0 on 2018-09-19 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writers', '0005_auto_20180919_0549'),
    ]

    operations = [
        migrations.AddField(
            model_name='writersprofile',
            name='country',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
