# Generated by Django 2.0 on 2018-09-20 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writers', '0006_writersprofile_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='writersprofile',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
