# Generated by Django 2.0 on 2018-09-20 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writers', '0007_writersprofile_is_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='writersprofile',
            name='country',
        ),
        migrations.RemoveField(
            model_name='writersprofile',
            name='subject_one',
        ),
        migrations.RemoveField(
            model_name='writersprofile',
            name='subject_three',
        ),
        migrations.RemoveField(
            model_name='writersprofile',
            name='subject_two',
        ),
        migrations.AddField(
            model_name='writersprofile',
            name='terms_condition',
            field=models.BooleanField(default=False),
        ),
    ]
