# Generated by Django 2.0 on 2018-09-20 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('writers', '0008_auto_20180920_0828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='writersprofile',
            name='terms_condition',
        ),
    ]
