# Generated by Django 2.0 on 2018-09-20 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writers', '0009_remove_writersprofile_terms_condition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='writersprofile',
            name='payment_method',
        ),
        migrations.AlterField(
            model_name='writersprofile',
            name='paypal_id',
            field=models.CharField(default='w', max_length=50),
            preserve_default=False,
        ),
    ]
