# Generated by Django 2.0 on 2018-09-21 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writers', '0010_auto_20180920_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writersprofile',
            name='image',
            field=models.ImageField(upload_to='profile_image'),
        ),
    ]
