# Generated by Django 2.0 on 2018-09-22 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writers', '0011_auto_20180920_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='writersprofile',
            name='profile_set',
            field=models.BooleanField(default=False),
        ),
    ]
