# Generated by Django 2.0 on 2018-09-25 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writers', '0012_writersprofile_profile_set'),
    ]

    operations = [
        migrations.AddField(
            model_name='bids',
            name='is_writer',
            field=models.BooleanField(default=False),
        ),
    ]
