# Generated by Django 2.0 on 2018-09-25 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writers', '0013_bids_is_writer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bids',
            name='is_writer',
        ),
        migrations.AddField(
            model_name='writersprofile',
            name='is_writer',
            field=models.BooleanField(default=False),
        ),
    ]
