# Generated by Django 2.0 on 2018-10-01 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0032_auto_20181001_1131'),
        ('writers', '0016_auto_20180928_1433'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvitedWriters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invited', models.BooleanField(default=False)),
                ('invitees', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitees', to='writers.WritersProfile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invited_writers', to='customer.Order')),
            ],
        ),
        migrations.AlterField(
            model_name='rating',
            name='rating_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='writers.WritersProfile'),
        ),
    ]
