# Generated by Django 2.0 on 2018-10-11 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('writers', '0019_bids_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bids',
            name='uuid',
        ),
    ]
