# Generated by Django 2.0 on 2018-10-11 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writers', '0020_remove_bids_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='bids',
            name='date_created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
