# Generated by Django 2.0 on 2018-10-15 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writers', '0023_assignmentfiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentfiles',
            name='description',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
