# Generated by Django 2.0 on 2018-10-17 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writers', '0024_assignmentfiles_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentfiles',
            name='id',
            field=models.CharField(max_length=7, primary_key=True, serialize=False),
        ),
    ]
