# Generated by Django 2.0 on 2018-10-17 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writers', '0026_auto_20181017_0554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bids',
            name='id',
            field=models.AutoField(max_length=7, primary_key=True, serialize=False),
        ),
    ]
