# Generated by Django 2.0 on 2018-10-19 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writers', '0027_auto_20181017_0559'),
    ]

    operations = [
        migrations.AddField(
            model_name='bids',
            name='bid_placed',
            field=models.BooleanField(default=False),
        ),
    ]
