# Generated by Django 2.0 on 2018-10-19 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writers', '0029_remove_bids_bid_placed'),
    ]

    operations = [
        migrations.AddField(
            model_name='bids',
            name='bid_placed',
            field=models.BooleanField(default=False),
        ),
    ]
