# Generated by Django 2.0 on 2018-10-22 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('writers', '0030_bids_bid_placed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bids',
            name='bid_placed',
        ),
    ]
